### ISSUE TITLE
Human: standard or variant (PBR, SRD only standard, PHB, ZEN)

### ISSUE THREAD

**Issue by incomingstick** [incomingstick/OpenRPG#53]
Add a namelist for Human

Are namelists against the OGL?

- [x] [PBR](http://dnd.wizards.com/articles/features/basicrules)
- [x] [SRD](https://dnd.wizards.com/articles/features/systems-reference-document-srd) only standard
- [x] PHB
- [x] [ZEN](http://media.wizards.com/2016/downloads/magic/Plane%20Shift%20Zendikar.pdf)
- [ ] Character Creator working

**Comment by Laviswalt** [comment]
confirmed

**Comment by incomingstick** [comment]
The Human and Human variant are technically already able to be made as characters, however the Character Generator is still in progress so I will not check this off as complete until the Character Generator itself is indeed working.
