### ISSUE TITLE
Changeling: (UA: “Eberron”)

### ISSUE THREAD

**Issue by incomingstick** [incomingstick/OpenRPG#73]
Add a namelist for Changeling

Are namelists against the OGL?

- [X] [UA: "Eberron"](https://media.wizards.com/2015/downloads/dnd/UA_Eberron_v1.pdf)
- [ ] Character Creator working

**Comment by Laviswalt** [comment]
confirmed

**Comment by incomingstick** [comment]
Next step: Be able to create a Changeling
