### ISSUE TITLE
Kor (ZEN)

### ISSUE THREAD

**Issue by incomingstick** [incomingstick/OpenRPG#75]
Add a namelist for Kor

Are namelists against the OGL?

- [ ] [ZEN](http://media.wizards.com/2016/downloads/magic/Plane%20Shift%20Zendikar.pdf)
- [ ] Character Creator working

**Comment by Laviswalt** [comment]
? unknown, tracked down source to some place one a 4e fansite, namelist probably not from zen

**Comment by incomingstick** [comment]
Let's make sure we cross reference and add any missing names
