### ISSUE TITLE
Minotaur (UA: “Waterborne Adventures”)

### ISSUE THREAD

**Issue by incomingstick** [incomingstick/OpenRPG#76]
Add a namelist for Minotaur

Are namelists against the OGL?

- [X] [UA: "Waterborne Adventures"](https://media.wizards.com/2015/downloads/dnd/UA_Waterborne_v3.pdf)
- [ ] Character Creator working

**Comment by Laviswalt** [comment]
confirmed

**Comment by incomingstick** [comment]
Next step: Be able to create a Minotaur
