### ISSUE TITLE
Tiefling: Infernal and Abyssal variants (UA: “That Old Black Magic”)

### ISSUE THREAD

**Issue by incomingstick** [incomingstick/OpenRPG#77]
Add a namelist for Tiefling

Are namelists against the OGL?

- [X] [UA: "That Old Black Magic"](https://media.wizards.com/2015/downloads/dnd/07_UA_That_Old_Black_Magic.pdf)
- [ ] Character Creator working

**Comment by Laviswalt** [comment]
confirmed
