### ISSUE TITLE
Warforged: (UA: “Eberron”)

### ISSUE THREAD

**Issue by incomingstick** [incomingstick/OpenRPG#81]
Add a namelist for Warforged

Are namelists against the OGL?

- [x] [UA: "Eberron"](https://media.wizards.com/2015/downloads/dnd/UA_Eberron_v1.pdf)
- [ ] Character Creator working

**Comment by Laviswalt** [comment]
confirmed

**Comment by incomingstick** [comment]
Next step: Be able to create a Warforged
